// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEoMxBeQia6EcUcABsLKnLYkiACw0kzyE',
    appId: '1:822686105489:web:a56a9a6ddd7e46c8de2430',
    messagingSenderId: '822686105489',
    projectId: 'flutter-shop-eef48',
    authDomain: 'flutter-shop-eef48.firebaseapp.com',
    storageBucket: 'flutter-shop-eef48.appspot.com',
    measurementId: 'G-HHS1JVHDY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE9fiIdTTBXxeCz438s_8elOHiW_Bu-lg',
    appId: '1:822686105489:android:a6111ec2e53d1618de2430',
    messagingSenderId: '822686105489',
    projectId: 'flutter-shop-eef48',
    storageBucket: 'flutter-shop-eef48.appspot.com',
  );
}
